### ISSUE TITLE
Works on UE50JU6800, but not when in standby

### ISSUE THREAD

**Issue by Jeroen-R** [tdudek/samsung-remote-models-2014-and-newer#9]
See title

I can use it to turn the TV off, but not on, which is what I need it for really.

When tv is in standby, it is stuck on 'Initializing device configuration'

**Comment by McKael** [comment]
When the TV is is standby, its network is down AFAICS.  So I doubt you can wake it up this way.

**Comment by jritmeijer-muhimbi** [comment]
That is what I thought. Looks like Samsung has really dropped the ball on this TV. 

I have ordered a broadlink mini3, to send IR via Wifi. It should do the trick.

**Comment by tdudek** [comment]
@Jeroen-R I experienced the same with my TV :-( We already discussed this in #1 

My current workaround is HDMI-CEC with a Raspberry Pi which is located next to the TV anyway.
You can find a simple example here https://github.com/tdudek/node-cec-remote 
For some reason I have to send the power-on command twice in order to really turn on the TV, but it works quite good.
